sudo: false
language: c
env:
  global:
addons:
  apt:
    packages:
    - docbook
    - docbook-dsssl
    - docbook-xsl
    - libbsd-dev
    - libedit-dev
    - libosp5
    - libostyle1c2
    - libpam0g-dev
    - libperl-dev
    - libperl5.14
    - libpython3.2
    - openjade
    - opensp
    - python3
    - python3-dev
    - python3-minimal
    - python3.2
    - python3.2-dev
    - python3.2-minimal
    - tcl8.5
    - tcl8.5-dev
    - xsltproc
script:
  - ./configure
  - make docs
  - make -C src/bin/psql sql_help.h
  - cd doc/src/sgml
  - xmllint --noout --valid postgres.xml
